/*
 * generated by Xtext 2.21.0
 */
package mdsd.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractMathCompilerScopeProvider extends DelegatingScopeProvider {
}
