/*
 * generated by Xtext 2.21.0
 */
package mdsd.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractMathCompilerValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(mdsd.mathCompiler.MathCompilerPackage.eINSTANCE);
		return result;
	}
}
