/**
 * generated by Xtext 2.21.0
 */
package mdsd.mathCompiler;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>External</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.mathCompiler.External#getBase <em>Base</em>}</li>
 *   <li>{@link mdsd.mathCompiler.External#getExponent <em>Exponent</em>}</li>
 * </ul>
 *
 * @see mdsd.mathCompiler.MathCompilerPackage#getExternal()
 * @model
 * @generated
 */
public interface External extends Expression
{
  /**
   * Returns the value of the '<em><b>Base</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Base</em>' attribute.
   * @see #setBase(int)
   * @see mdsd.mathCompiler.MathCompilerPackage#getExternal_Base()
   * @model
   * @generated
   */
  int getBase();

  /**
   * Sets the value of the '{@link mdsd.mathCompiler.External#getBase <em>Base</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Base</em>' attribute.
   * @see #getBase()
   * @generated
   */
  void setBase(int value);

  /**
   * Returns the value of the '<em><b>Exponent</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exponent</em>' attribute.
   * @see #setExponent(int)
   * @see mdsd.mathCompiler.MathCompilerPackage#getExternal_Exponent()
   * @model
   * @generated
   */
  int getExponent();

  /**
   * Sets the value of the '{@link mdsd.mathCompiler.External#getExponent <em>Exponent</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exponent</em>' attribute.
   * @see #getExponent()
   * @generated
   */
  void setExponent(int value);

} // External
