/**
 * generated by Xtext 2.21.0
 */
package mdsd.mathCompiler;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link mdsd.mathCompiler.Var#getId <em>Id</em>}</li>
 * </ul>
 *
 * @see mdsd.mathCompiler.MathCompilerPackage#getVar()
 * @model
 * @generated
 */
public interface Var extends Expression
{
  /**
   * Returns the value of the '<em><b>Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Id</em>' attribute.
   * @see #setId(String)
   * @see mdsd.mathCompiler.MathCompilerPackage#getVar_Id()
   * @model
   * @generated
   */
  String getId();

  /**
   * Sets the value of the '{@link mdsd.mathCompiler.Var#getId <em>Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Id</em>' attribute.
   * @see #getId()
   * @generated
   */
  void setId(String value);

} // Var
