/*
 * generated by Xtext 2.21.0
 */
package mdsd.ui.tests;

import com.google.inject.Injector;
import mdsd.mathcompiler.ui.internal.MathcompilerActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MathCompilerUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MathcompilerActivator.getInstance().getInjector("mdsd.MathCompiler");
	}

}
